# Generated by Django 6.0.1 on 2026-01-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(help_text='支持 HTML 格式', verbose_name='公告内容')),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '实验室公告',
                'verbose_name_plural': '实验室公告',
                'ordering': ['-is_top', '-created_at'],
            },
        ),
    ]
