# Generated by Django 6.0.1 on 2026-01-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('title', models.CharField(help_text='例如: 教授 / 博士生导师', max_length=50, verbose_name='头衔')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='faculty/', verbose_name='照片')),
                ('intro', models.TextField(verbose_name='个人简介')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('homepage', models.URLField(blank=True, verbose_name='个人主页链接')),
            ],
            options={
                'verbose_name': '导师/教职工',
                'verbose_name_plural': '导师/教职工',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='论文标题')),
                ('authors', models.CharField(help_text='例如: Zhang San, Li Si, et al.', max_length=200, verbose_name='作者列表')),
                ('venue', models.CharField(help_text='例如: CVPR 2025', max_length=100, verbose_name='发表刊物/会议')),
                ('year', models.IntegerField(default=2026, verbose_name='发表年份')),
                ('link', models.URLField(blank=True, help_text='跳转到 PDF 或 Arxiv', verbose_name='论文链接')),
                ('is_highlight', models.BooleanField(default=False, verbose_name='设为高亮/代表作')),
            ],
            options={
                'verbose_name': '论文成果',
                'verbose_name_plural': '论文成果',
                'ordering': ['-year', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='方向名称')),
                ('description', models.TextField(verbose_name='方向简介')),
                ('icon', models.CharField(default='🔬', help_text='例如: 🔬, 💻, 🧬', max_length=10, verbose_name='图标Emoji')),
            ],
            options={
                'verbose_name': '研究方向',
                'verbose_name_plural': '研究方向',
            },
        ),
    ]
