# Generated by Django 6.0.1 on 2026-01-29 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_faculty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='班级名称')),
                ('description', models.TextField(blank=True, verbose_name='班级简介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(limit_choices_to={'status': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentored_classes', to=settings.AUTH_USER_MODEL, verbose_name='负责导师')),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'status': 'student'}, related_name='lab_classes', to=settings.AUTH_USER_MODEL, verbose_name='班级成员')),
            ],
            options={
                'verbose_name': '行政班级',
                'verbose_name_plural': '行政班级',
                'ordering': ['-created_at'],
            },
        ),
    ]
