# Generated by Django 6.0.1 on 2026-01-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='标签名')),
                ('slug', models.SlugField(allow_unicode=True, max_length=30, unique=True, verbose_name='URL标识')),
                ('color', models.CharField(default='#6c757d', help_text='十六进制颜色，如 #FF0000', max_length=7, verbose_name='颜色代码')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='community.tag', verbose_name='标签'),
        ),
    ]
