# Generated by Django 6.0.1 on 2026-01-30 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_comment_likes_post_is_first_like_rewarded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', '🌍 公开'), ('private', '🔒 仅自己可见')], default='public', max_length=10, verbose_name='可见性'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='收藏夹名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开收藏夹')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posts', models.ManyToManyField(blank=True, related_name='collected_in', to='community.post', verbose_name='收藏的帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '收藏夹',
                'verbose_name_plural': '收藏夹',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
