# Generated by Django 6.0.1 on 2026-01-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_customuser_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('name', models.CharField(blank=True, help_text='选填，用于管理员备注', max_length=50, verbose_name='真实姓名')),
            ],
            options={
                'verbose_name': '学号白名单',
                'verbose_name_plural': '学号白名单',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('newbie', '🌱 新生'), ('student', '🎓 在读'), ('alumni', '🏆 毕业')], default='newbie', max_length=10, verbose_name='当前身份'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, help_text='认证通过后绑定', max_length=20, null=True, unique=True, verbose_name='学号'),
        ),
    ]
