# Generated by Django 6.0.1 on 2026-01-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_studentwhitelist_customuser_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coins',
            field=models.PositiveIntegerField(default=0, verbose_name='硬币'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='growth',
            field=models.PositiveIntegerField(default=0, verbose_name='成长值'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='等级'),
        ),
    ]
