# Generated by Django 6.0.1 on 2026-01-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_customuser_coins_customuser_growth_customuser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='detailed_intro',
            field=models.TextField(blank=True, help_text='仅导师身份生效，支持 Markdown 语法', verbose_name='详细介绍 (Markdown)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('newbie', '🌱 新生'), ('student', '🎓 在读'), ('alumni', '🏆 毕业'), ('faculty', '👨\u200d🏫 导师')], default='newbie', max_length=10, verbose_name='当前身份'),
        ),
    ]
