# Generated by Django 6.0.1 on 2026-01-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_customuser_detailed_intro_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='detailed_intro',
            field=models.TextField(blank=True, help_text='支持 Markdown 语法。用于在实验室介绍页展示个人简历、研究兴趣等。', verbose_name='详细介绍 (Markdown)'),
        ),
    ]
