# Generated by Django 6.0.1 on 2026-02-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enable_ebbinghaus',
            field=models.BooleanField(default=False, help_text='开启后，系统将根据遗忘曲线发送复习提醒邮件', verbose_name='开启艾宾浩斯提醒'),
        ),
    ]
