# Generated by Django 6.0.1 on 2026-01-28 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='任务标题')),
                ('content', models.TextField(verbose_name='任务详情 (支持Markdown)')),
                ('bounty', models.PositiveIntegerField(default=0, help_text='任务结束时将支付给贡献最大者', verbose_name='悬赏金币')),
                ('status', models.CharField(choices=[('open', '🔥 招募中'), ('in_progress', '🚀 进行中'), ('closed', '🏁 已结束')], default='open', max_length=20, verbose_name='状态')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tasks', to=settings.AUTH_USER_MODEL, verbose_name='最终获胜者')),
            ],
            options={
                'verbose_name': '悬赏任务',
                'verbose_name_plural': '悬赏任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', '📩 待回应'), ('accepted', '✅ 已接受'), ('rejected', '🚫 已拒绝'), ('quit', '🏳️ 中途放弃')], default='invited', max_length=20, verbose_name='参与状态')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tasks.task', verbose_name='关联任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_participations', to=settings.AUTH_USER_MODEL, verbose_name='参与者')),
            ],
            options={
                'verbose_name': '参与记录',
                'verbose_name_plural': '参与记录',
                'unique_together': {('task', 'user')},
            },
        ),
    ]
