# Generated by Django 6.0.1 on 2026-01-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-task_type', '-created_at'], 'verbose_name': '悬赏任务', 'verbose_name_plural': '悬赏任务'},
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('bounty', '💰 悬赏任务'), ('faculty', '🚨 导师指令')], default='bounty', max_length=10, verbose_name='任务类型'),
        ),
    ]
