# Generated by Django 6.0.1 on 2026-01-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_class_task',
            field=models.BooleanField(default=False, verbose_name='是否班级任务'),
        ),
    ]
