# Generated by Django 6.0.1 on 2026-02-06 16:26

import django.db.models.deletion
import innovation_agent.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='未命名创新项目', max_length=100, verbose_name='项目名称')),
                ('status', models.IntegerField(choices=[(0, '等待上传 Baseline'), (1, '正在解析 Baseline'), (2, '创新点 1 构思中'), (3, '创新点 2 构思中'), (4, '创新点 3 构思中'), (5, '实验设计中'), (6, '已完成')], default=0, verbose_name='当前状态')),
                ('baseline_file', models.FileField(blank=True, null=True, upload_to=innovation_agent.models.project_file_path, verbose_name='Baseline PDF')),
                ('base_md_content', models.TextField(blank=True, verbose_name='Baseline 总结 (MD)')),
                ('innov1_md_content', models.TextField(blank=True, verbose_name='创新点 1 (MD)')),
                ('innov2_md_content', models.TextField(blank=True, verbose_name='创新点 2 (MD)')),
                ('innov3_md_content', models.TextField(blank=True, verbose_name='创新点 3 (MD)')),
                ('exp_md_content', models.TextField(blank=True, verbose_name='实验设计 (MD)')),
                ('final_report', models.FileField(blank=True, null=True, upload_to=innovation_agent.models.project_file_path, verbose_name='最终报告 PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovation_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '创新项目',
                'verbose_name_plural': '创新项目',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek (推荐)'), ('openai', 'OpenAI (GPT-4)'), ('anthropic', 'Claude'), ('custom', '自定义 (Compatible)')], default='deepseek', max_length=20, verbose_name='服务商')),
                ('base_url', models.CharField(default='https://api.deepseek.com/v1', help_text='API 请求地址', max_length=255, verbose_name='Base URL')),
                ('model_name', models.CharField(default='deepseek-chat', help_text='例如: gpt-4, deepseek-reasoner', max_length=50, verbose_name='模型名称')),
                ('encrypted_api_key', models.CharField(blank=True, max_length=500, verbose_name='API Key (加密)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM 配置',
                'verbose_name_plural': 'LLM 配置',
            },
        ),
    ]
