# Generated by Django 6.0.1 on 2026-02-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationproject',
            name='total_tokens_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Token 总消耗'),
        ),
    ]
