# Generated by Django 6.0.1 on 2026-02-06 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation_agent', '0002_innovationproject_total_tokens_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI'), ('system', '系统提示')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='innovation_agent.innovationproject')),
            ],
            options={
                'verbose_name': '项目聊天记录',
                'verbose_name_plural': '项目聊天记录',
                'ordering': ['created_at'],
            },
        ),
    ]
