# Generated by Django 6.0.1 on 2026-01-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_email_sent',
            field=models.BooleanField(default=False, verbose_name='已发送邮件提醒'),
        ),
    ]
