"""
Django settings for myweb project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import os

load_dotenv() # 👈 加载 .env 文件
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=%xw9+le5$nbl*!+e27i9z2wfui+(#bos3!n^xx68a2%anw3=t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['49.234.26.95']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user_app',
    'core',  # 👈 新增：这是我们的门面
    'Github_trend',
    'community', # 👈 新增：社区/论坛
    'notifications', # 👈 新增
    'news', # 👈 新增
    # 👇 新增：全文检索框架
    'haystack',
    'direct_messages', # 👈 新增
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 👇 修改这里，告诉 Django 去根目录的 templates 找文件
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.unread_count', # 👈 新增
            ],
        },
    },
]

WSGI_APPLICATION = 'myweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] # 确保这一行存在

AUTH_USER_MODEL = 'user_app.CustomUser'

# 2. 媒体文件配置 (用于存放头像)
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 登录成功后跳转的 URL (对应 urls.py 里的 name)
# 注意：因为我们用了 app_name='user_app'，所以这里要加上前缀
LOGIN_REDIRECT_URL = 'home'
# 登出后也跳回大厅
LOGOUT_REDIRECT_URL = 'home'

# 指定认证后端
AUTHENTICATION_BACKENDS = [
    'user_app.authentication.EmailBackend',  # 我们刚写的，排在第一位
    'django.contrib.auth.backends.ModelBackend', # 保留 Django 原生的作为兜底
]

# 邮件配置 (开发环境专用)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# 以后上线了再改成 smtp.gmail.com


# 缓存配置 (开发环境使用内存缓存)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
LOGIN_URL = 'user_app:login'


# ==================================
# Celery 配置
# ==================================
# Broker: 消息中间件，负责存储任务队列。这里使用 Redis。
# 格式: redis://:密码@IP:端口/数据库号
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'

# Backend: 结果存储后端，用于存储任务的执行结果（可选，如果不需要看结果可以不配）
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1'

# 时区设置（跟随 Django）
CELERY_TIMEZONE = TIME_ZONE

# 防止死锁建议配置 (可选)
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 单个任务最大运行时间 (30分钟)

# ==================================
# Haystack + Whoosh 全文检索配置
# ==================================
HAYSTACK_CONNECTIONS = {
    'default': {
        # 指定使用 Whoosh 引擎
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        # 索引文件存储路径 (会自动创建)
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    },
}

# 自动更新索引 (当有新帖子发布/修改时，自动更新搜索索引)
# 注意：这会轻微影响保存速度，如果数据量巨大建议用 Celery 异步更新
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'