"""
Django settings for myweb project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# 👈 加载 .env 文件中的环境变量
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=%xw9+le5$nbl*!+e27i9z2wfui+(#bos3!n^xx68a2%anw3=t'

# SECURITY WARNING: don't run with debug turned on in production!
# ⚠️ 注意：正式上线请改为 False
DEBUG = True

ALLOWED_HOSTS = ['49.234.26.95', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user_app',
    'core',  # 👈 门面应用
    'Github_trend',
    'community', # 👈 社区/论坛
    'notifications', # 👈 消息通知
    'news', # 👈 公告
    'haystack', # 👈 全文检索
    'direct_messages', # 👈 私信
    'tasks', # 👈 新增这一行
    'npy_editor',
    'vocabulary', # 👈 新增这一行
    'innovation_agent', # 👈 新增
    # 👇 新增这一行
    'cyber_fortune', # 👈 赛博祈福
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 👈 告诉 Django 去根目录的 templates 找文件
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.unread_count', # 👈 消息计数
            ],
        },
    },
]

WSGI_APPLICATION = 'myweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] # 确保这一行存在

# 自定义用户模型
AUTH_USER_MODEL = 'user_app.CustomUser'

# 媒体文件配置 (用于存放头像)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 登录相关跳转
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'user_app:login'

# 指定认证后端
AUTHENTICATION_BACKENDS = [
    'user_app.authentication.EmailBackend',  # 自定义邮箱登录
    'django.contrib.auth.backends.ModelBackend', # 原生兜底
]

# ==================================
# 📧 真实邮件发送配置 (SMTP)
# ==================================
# 使用 SMTP 后端，不再是 console
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')         # 例如 smtp.qq.com
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587)) # SSL 端口通常是 465
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER') # 你的邮箱地址
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD') # 你的授权码
# 👇👇👇 核心修改开始 👇👇👇
# 改为使用 TLS (Transport Layer Security)
# 很多云服务器对 SSL(465) 的握手处理有问题，改用 TLS(587) 通常能解决 "Connection unexpectedly closed"
EMAIL_USE_TLS = True   # 👈 开启 TLS
EMAIL_USE_SSL = False  # 👈 关闭 SSL (这两个不能同时为 True)
# 👆👆👆 核心修改结束 👆👆👆

EMAIL_FROM = EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# 缓存配置 (开发环境使用内存缓存)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}


# ==================================
# Celery 配置
# ==================================
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

# ==================================
# Haystack + Whoosh 全文检索配置
# ==================================
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    },
}
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

# ==================================
# 消息框架配置 (修复白底白字问题)
# ==================================
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger', # 👈 关键：把 error 映射为 danger (红色背景)
}

SITE_URL = 'http://49.234.26.95:8218'