# Generated by Django 6.0.1 on 2026-01-31 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100, verbose_name='单词')),
                ('phonetic', models.CharField(blank=True, max_length=100, null=True, verbose_name='音标')),
                ('meaning', models.TextField(verbose_name='释义')),
                ('level', models.CharField(choices=[('CET4', '英语四级'), ('CET6', '英语六级')], db_index=True, max_length=10, verbose_name='等级')),
            ],
        ),
        migrations.CreateModel(
            name='UserWordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '未掌握'), (1, '已掌握')], default=0, verbose_name='状态')),
                ('last_reviewed', models.DateTimeField(auto_now=True, verbose_name='上次复习')),
                ('mistake_count', models.PositiveIntegerField(default=0, verbose_name='错误次数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_progress', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.word')),
            ],
            options={
                'ordering': ['-last_reviewed'],
                'unique_together': {('user', 'word')},
            },
        ),
    ]
