# Generated by Django 6.0.1 on 2026-01-31 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userwordprogress',
            options={},
        ),
        migrations.AddField(
            model_name='userwordprogress',
            name='is_mistake',
            field=models.BooleanField(default=False, verbose_name='是否在错题本'),
        ),
        migrations.AddField(
            model_name='word',
            name='example_cn',
            field=models.TextField(blank=True, null=True, verbose_name='例句翻译'),
        ),
        migrations.AddField(
            model_name='word',
            name='example_en',
            field=models.TextField(blank=True, null=True, verbose_name='英文例句'),
        ),
        migrations.AlterField(
            model_name='userwordprogress',
            name='status',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='userwordprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='单词'),
        ),
    ]
