# Generated by Django 6.0.1 on 2026-01-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_userwordprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userwordprogress',
            options={'ordering': ['-last_reviewed']},
        ),
        migrations.AddField(
            model_name='word',
            name='book_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='词书ID'),
        ),
        migrations.AddField(
            model_name='word',
            name='word_rank',
            field=models.IntegerField(default=0, verbose_name='排名'),
        ),
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.CharField(choices=[('CET4', '四级'), ('CET6', '六级')], db_index=True, max_length=10, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(db_index=True, max_length=100, verbose_name='单词'),
        ),
    ]
