# Generated by Django 6.0.1 on 2026-01-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_alter_userwordprogress_options_word_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.CharField(choices=[('CET4', '四级'), ('CET6', '六级'), ('TOEFL', '托福'), ('IELTS', '雅思'), ('KaoYan', '考研')], db_index=True, max_length=10, verbose_name='等级'),
        ),
    ]
