# Generated by Django 6.0.1 on 2026-02-17 10:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_alter_word_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EbbinghausBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(db_index=True, max_length=50, verbose_name='词书ID')),
                ('study_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='学习日期')),
                ('first_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='首次完成时间')),
                ('review_status', models.JSONField(blank=True, default=dict, verbose_name='复习状态矩阵')),
                ('total_review_count', models.PositiveIntegerField(default=0, verbose_name='累计复习次数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebbinghaus_batches', to=settings.AUTH_USER_MODEL)),
                ('words', models.ManyToManyField(related_name='batches', to='vocabulary.word', verbose_name='包含单词')),
            ],
            options={
                'verbose_name': '艾宾浩斯批次',
                'verbose_name_plural': '艾宾浩斯批次',
                'ordering': ['-study_date'],
                'unique_together': {('user', 'book_id', 'study_date')},
            },
        ),
    ]
