# Generated by Django 6.0.1 on 2026-02-20 12:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FortuneProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='降生参数 (出生日期)')),
                ('zodiac', models.CharField(blank=True, help_text='根据生日自动计算的专属星象', max_length=20, verbose_name='赛博星象')),
                ('monthly_luck_score', models.PositiveIntegerField(default=0, verbose_name='本月累计气运池')),
                ('last_reset_month', models.CharField(blank=True, help_text='格式: YYYY-MM，用于判断跨月清零', max_length=7, verbose_name='最后刷新月份')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fortune_profile', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '祈福档案',
                'verbose_name_plural': '祈福档案',
            },
        ),
        migrations.CreateModel(
            name='DailyBlessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bless_date', models.DateField(default=django.utils.timezone.now, verbose_name='祈福日期')),
                ('score', models.PositiveIntegerField(verbose_name='今日算力 (气运值)')),
                ('fortune_text', models.CharField(max_length=255, verbose_name='赛博吉言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录生成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blessings', to=settings.AUTH_USER_MODEL, verbose_name='祈福者')),
            ],
            options={
                'verbose_name': '每日祈福',
                'verbose_name_plural': '每日祈福',
                'ordering': ['-bless_date', '-created_at'],
                'unique_together': {('user', 'bless_date')},
            },
        ),
    ]
