# Generated by Django 6.0.1 on 2026-02-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_fortune', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortuneprofile',
            name='mbti',
            field=models.CharField(default='INTJ', max_length=4, verbose_name='MBTI 人格'),
        ),
        migrations.AddField(
            model_name='fortuneprofile',
            name='muyu_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='累计敲击木鱼次数'),
        ),
        migrations.AlterField(
            model_name='fortuneprofile',
            name='last_reset_month',
            field=models.CharField(blank=True, max_length=7, verbose_name='最后刷新月份'),
        ),
        migrations.AlterField(
            model_name='fortuneprofile',
            name='zodiac',
            field=models.CharField(blank=True, max_length=20, verbose_name='赛博星象'),
        ),
    ]
