# Generated by Django 6.0.1 on 2026-01-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('like', '点赞'), ('comment', '评论'), ('reply', '回复'), ('follow', '关注')], max_length=20, verbose_name='动作'),
        ),
    ]
