# Generated by Django 6.0.1 on 2026-01-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('like', '点赞'), ('comment', '评论'), ('reply', '回复'), ('follow', '关注'), ('system', '系统通知')], max_length=20, verbose_name='动作'),
        ),
    ]
