# Generated by Django 6.0.1 on 2026-01-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('like', '点赞'), ('comment', '评论'), ('reply', '回复'), ('follow', '关注'), ('system', '系统通知'), ('friend_request', '好友申请'), ('friend_accept', '通过好友'), ('friend_reject', '拒绝好友'), ('task_invite', '任务邀请'), ('task_accept', '接受任务'), ('task_reject', '拒绝任务'), ('task_settle', '任务结算')], max_length=20, verbose_name='动作'),
        ),
    ]
